name: deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Server
        run: |
          ssh -i /home/tydev/Desktop/mykeypair.pem ubuntu@3.92.84.56 'cd /home/ubuntu/my-fastapi-app && git pull && sudo systemctl restart fastapi'

